--- 
output_dir: output
deploy:
  default:
    dst:     "sleight42@tiggerpalace.com:/home/sleight42/coulda.tiggerpalace.com"
    options: [ '-gpPrvz', '--exclude=".git"' ]
data_sources: 
- items_root: /
  layouts_root: /
  type: filesystem_compact
